services:
  dev:
    tty: true
    stdin_open: true
    image: godot-rust-dev
    container_name: godot_rust_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash
    volumes:
      - ../:/workspace:Z
    working_dir: /workspace
